openapi: 3.0.0
info:
  title: module-update-router
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/channel:
    get:
      summary: Request a channel
      tags: []
      operationId: get-channel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
              examples:
                example-release:
                  value:
                    url: /release
                example-testing:
                  value:
                    url: /testing
      parameters:
        - schema:
            type: string
          in: query
          name: module
          required: true
  /api/v1/event:
    post:
      summary: Submit a run event
      tags: []
      operationId: post-event
      responses:
        "200":
          description: OK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phase:
                  type: string
                started:
                  type: string
                exit:
                  type: integer
                exception:
                  type: string
                duration:
                  type: string
components:
  schemas: {}
  securitySchemes: {}
