openapi: 3.0.0
info:
  title: module-update-router
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /api/v1/channel:
    get:
      summary: Request a channel
      tags: []
      operationId: get-channel
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
              examples:
                example-release:
                  value:
                    url: /release
                example-testing:
                  value:
                    url: /testing
      parameters:
        - schema:
            type: string
          in: query
          name: module
          required: true
  /api/v1/event:
    post:
      summary: Submit a run event
      tags: []
      operationId: post-event
      responses:
        "201":
          description: CREATED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phase
                - started_at
                - exit
                - ended_at
                - machine_id
                - core_version
              properties:
                phase:
                  type: string
                started_at:
                  type: string
                  format: date-time
                  example: "2006-01-02T15:04:05+00:00"
                exit:
                  type: integer
                exception:
                  type: string
                ended_at:
                  type: string
                  format: date-time
                  example: "2006-01-02T15:04:05+00:00"
                machine_id:
                  type: string
                core_version:
                  type: string
components:
  schemas: {}
  securitySchemes: {}
