---
apiVersion: v1
kind: Template
metadata:
  name: module-update-router
labels:
  app: module-update-router
parameters:
  - name: IMAGE
    description: The container image
    value: quay.io/cloudservices/module-update-router
  - name: IMAGE_TAG
    description: The container image tag
    value: latest
  - name: KAFKA_BOOTSTRAP_HOST
    value: mq-kafka
  - name: KAFKA_BOOTSTRAP_PORT
    value: "29092"
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: module-update-router
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: module-update-router
      template:
        metadata:
          labels:
            app: module-update-router
        spec:
          metadata:
            annotations:
              prometheus.io/path: /
              prometheus.io/port: "2112"
              prometheus.io/scrape: "true"
          imagePullSecrets:
            - name: quay-cloudservices-pull
            - name: rh-registry-pull
          initContainers:
            - name: migrate
              image: ${IMAGE}:${IMAGE_TAG}
              volumeMounts:
                - name: accounts-modules
                  mountPath: /seed
              args:
                - "-migrate"
                - "-seed-path=/seed/seed.sql"
                - "-log-level=debug"
              envFrom:
                - configMapRef:
                    name: module-update-router-config
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.user
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.password
          containers:
            - name: module-update-router
              image: ${IMAGE}:${IMAGE_TAG}
              envFrom:
                - configMapRef:
                    name: module-update-router-config
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.user
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.password
              ports:
                - containerPort: 8080
                - containerPort: 2112
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8080
                initialDelaySeconds: 30
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8080
                initialDelaySeconds: 10
          volumes:
            - name: accounts-modules
              secret:
                secretName: accounts-modules
  - apiVersion: v1
    kind: Service
    metadata:
      name: module-update-router
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      selector:
        app: module-update-router
      ports:
        - port: 8080
          targetPort: 8080
          name: app
        - port: 2112
          targetPort: 2112
          name: metrics
  - apiVersion: v1
    kind: Route
    metadata:
      name: module-update-router
    spec:
      to:
        kind: Service
        name: module-update-router
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: module-update-router-config
    data:
      PATH_PREFIX: /api,/r/insights/platform
      APP_NAME: module-update-router
      DB_DRIVER: pgx
      KAFKA_BOOTSTRAP: "${KAFKA_BOOTSTRAP_HOST}:${KAFKA_BOOTSTRAP_PORT}"
      METRICS_TOPIC: platform.insights.client-metrics
  - apiVersion: v1
    kind: Secret
    metadata:
      name: accounts-modules
    data:
      seed.sql: QkVHSU47Q09NTUlUOwo=
