---
apiVersion: v1
kind: Template
metadata:
  name: module-update-router
labels:
  app: module-update-router
parameters:
  - name: IMAGE
    description: The container image
    value: quay.io/cloudservices/module-update-router
  - name: IMAGE_TAG
    description: The container image tag
    value: latest
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: module-update-router
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: module-update-router
      template:
        metadata:
          labels:
            app: module-update-router
        spec:
          imagePullSecrets:
            - name: quay-cloudservices-pull
            - name: rh-registry-pull
          initContainers:
            - name: migrate
              image: ${IMAGE}:${IMAGE_TAG}
              volumeMounts:
                - name: accounts-modules
                  mountPath: /seed
              args:
                - "-migrate"
                - "-seed-path=/seed/seed.sql"
              envFrom:
                - configMapRef:
                    name: module-update-router-stage-config
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.user
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.password
          containers:
            - name: module-update-router
              image: ${IMAGE}:${IMAGE_TAG}
              envFrom:
                - configMapRef:
                    name: module-update-router-stage-config
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.user
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: module-update-router-db
                      key: db.password
              ports:
                - containerPort: 8080
                - containerPort: 2112
          volumes:
            - name: accounts-modules
              secret:
                secretName: accounts-modules
  - apiVersion: v1
    kind: Service
    metadata:
      name: module-update-router
    spec:
      selector:
        app: module-update-router
      ports:
        - port: 8080
          targetPort: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      name: module-update-router
    spec:
      to:
        kind: Service
        name: module-update-router
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: module-update-router-stage-config
    data:
      PATH_PREFIX: /api
      APP_NAME: module-update-router
      LOG_LEVEL: trace
      ENVIRONMENT: production
